#!/bin/bash
#Author Suresh
#description: variable concepts

name="Suresh"
a=20
b=30

#to call a variable value we use ${}
echo "my name is ${name}"
#to call a command inside the string we use $()
echo "Today's date is $(date +%D)"
